public class TryCatch3 {

    public static int[] Array = new int[10]; // dichiarazione array
    public static void main(String[] args) {
        for (Integer i=0; i<Array.length;i++);
            
        try {
        
            Array[10]=2; // se scrivo Array[10]=20 mi da errore, ma il problema è che anche così mi stampa Errore, in teoria non dovrebbe farlo
            if (Array[10]<Array.length){
            System.out.println(Array);}
           
        }catch (ArrayIndexOutOfBoundsException x){ 
            System.out.println("Errore");
            }
        }
    }
    
